services:
  mysql:
    container_name: mysql_container
    image: mysql:8.0
    ports:
      - 3306:3306
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=mysql
      - MYSQL_USER=mysql
      - MYSQL_PASSWORD=mysql
      - MYSQL_ROOT_PASSWORD=root_password
      - TZ=Asia/Seoul
    shm_size: 2GB
    deploy:
      resources:
        limits:
          memory: 8G
    command: |
      mysqld
        --character-set-server=utf8mb4
        --collation-server=utf8mb4_unicode_ci
        --default-time-zone=Asia/Seoul
        --innodb-redo-log-capacity=1G
        --innodb-buffer-pool-size=4G
        --innodb-log-buffer-size=64M
        --innodb-flush-log-at-trx-commit=2
        --innodb-file-per-table=1
        --innodb-flush-method=O_DIRECT
        --max-connections=300
        --thread_cache_size=100
        --tmp_table_size=128M
        --max_heap_table_size=128M
        --sort_buffer_size=8M
        --join_buffer_size=8M
        --key_buffer_size=64M
        --read_buffer_size=8M
        --read_rnd_buffer_size=8M
        --table_open_cache=4000
        --open_files_limit=65535
        --innodb_read_io_threads=8
        --innodb_write_io_threads=8
        --innodb_io_capacity=4000
        --innodb_io_capacity_max=8000
        --innodb_flush_neighbors=0
        --innodb_purge_threads=8
